=== adamkubina1/4iz238-final/pruvodce.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="urn:Test.Namespace" 
    xmlns="urn:Test.Namespace" 
    xmlns:p="urn:Test.Namespace"
        elementFormDefault="qualified">
    
    <xs:element name="průvodce" type="PrůvodceTyp"/>
    
    <xs:complexType name="PrůvodceTyp">
        <xs:sequence>
            <xs:element name="názevDíla" type="AutorTyp"/>
            <xs:element name="autor" type="AutorTyp"/>
            <xs:element name="památky" type="PamátkyTyp">
                <xs:key name="nazev_pamatky_unikatni">
                    <xs:selector xpath="p:památka"></xs:selector>
                    <xs:field xpath="p:název"></xs:field>
                </xs:key>
                
                <xs:keyref refer="nazev_pamatky_unikatni" name="pamatka_pobliz_existuje">
                    <xs:selector xpath="p:památka"></xs:selector>
                    <xs:field xpath="p:památkaPoblíž"></xs:field>
                </xs:keyref>
            </xs:element>            
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="AutorTyp">
        <xs:restriction base="xs:string">
            <xs:maxLength value="40"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="PamátkyTyp">
        <xs:sequence>
            <xs:element name="památka" type="PamátkaTyp" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PamátkaTyp">
        <xs:sequence>
            <xs:element name="název" type="NázevTyp"/>
            <xs:element name="postaven" type="PostavenTyp"/>
            <xs:element name="oblíbenost" type="OblíbenostTyp"/>
            <xs:element name="památkaPoblíž" type="AutorTyp"/>
            <xs:element name="umístění" type="UmístěníTyp"/>
            <xs:element name="sloh" type="AutorTyp"/>
            <xs:element name="foto" type="FotoTyp"/>
            <xs:element name="popis" type="PopisTyp"/>
            <xs:element name="zajímavost" type="ZajímavostTyp"/>
            <xs:element name="majitelé" type="MajiteléTyp"/>
            <xs:element name="navštívitelný" type="NavštívitelnýTyp"/>
            <xs:element name="vstupné" type="VstupnéTyp"/>
            <xs:element name="přístupnost" type="PřístupnostTyp"/>
            <xs:element name="služby" type="SlužbyTyp"/>
            <xs:element name="reference" type="ReferenceTyp"/>
            <xs:element name="webovky" type="WebTyp"/>
        </xs:sequence>
        <xs:attribute name="druh" type="DruhTyp" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="NázevTyp">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:integer"/>
            </xs:extension>
    </xs:simpleContent>
    </xs:complexType>
    
    <xs:simpleType name="DruhTyp">
        <xs:restriction base="xs:string">
            <xs:enumeration value="hrad"/>
            <xs:enumeration value="zámek"/>
            <xs:enumeration value="jiné"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="PostavenTyp">        
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="upřesnění" type="UpřesněníTyp" use="required"/>  
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    

    <xs:simpleType name="UpřesněníTyp">
        <xs:restriction base="xs:string">
            <xs:pattern value="rok|století"/>            
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="OblíbenostTyp">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0.0"/>
            <xs:maxInclusive value="5.0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="UmístěníTyp">
        <xs:all>
            <xs:element name="kraj" type="KrajTyp" maxOccurs="1"/>
            <xs:element name="mapa" type="WebTyp"/>
        </xs:all>
    </xs:complexType>
    
    <xs:simpleType name="KrajTyp">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Praha"/>
            <xs:enumeration value="Středočeský kraj"/>
            <xs:enumeration value="Karlovarský kraj"/>
            <xs:enumeration value="Ústecký kraj"/>
            <xs:enumeration value="Liberecký kraj"/>
            <xs:enumeration value="Královehradecký kraj"/>
            <xs:enumeration value="Pardubický kraj"/>
            <xs:enumeration value="Plzeňský kraj"/>
            <xs:enumeration value="Jihočeský kraj"/>
            <xs:enumeration value="kraj Vysočina"/>
            <xs:enumeration value="Vysočina"/>
            <xs:enumeration value="Jihomoravský kraj"/>
            <xs:enumeration value="Olomoucký kraj"/>
            <xs:enumeration value="Zlínský kraj"/>  
            <xs:enumeration value="Moravskoslezský kraj"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="WebTyp">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="href" type="xs:anyURI" use="optional"/>        
            </xs:extension>
        </xs:simpleContent>        
    </xs:complexType>
    
    <xs:complexType name="FotoTyp">
        <xs:attribute name="src"></xs:attribute>
    </xs:complexType>
    
    <xs:simpleType name="PopisTyp">
        <xs:restriction base="xs:string">
            <xs:minLength value="100"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="ZajímavostTyp" >
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
        
    <xs:complexType name="MajiteléTyp">
        <xs:sequence>
            <xs:element name="majitel" type="AutorTyp" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="NavštívitelnýTyp">
        <xs:restriction base="xs:string">
            <xs:pattern value="ano"/>
            <xs:pattern value="ne"/>
            <xs:whiteSpace value="collapse"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="VstupnéTyp">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="měna" type="MěnaTyp" use="required"/>  
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:simpleType name="MěnaTyp">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Kč"/>
            <xs:enumeration value="Euro"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="PřístupnostTyp">
        <xs:sequence>
            <xs:element name="kategorie" type="AutorTyp" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="SlužbyTyp">
        <xs:sequence>
            <xs:element name="služba" type="AutorTyp" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="ReferenceTyp">
        <xs:sequence>
            <xs:element name="hodnocení" type="HodnoceníTyp" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="HodnoceníTyp">
        <xs:sequence>
            <xs:element name="počet_hvězd" type="OblíbenostTyp"/>
            <xs:element name="datum" type="xs:date"/>
            <xs:element name="komentář" type="ZajímavostTyp"/>
        </xs:sequence>
    </xs:complexType>
    
    
</xs:schema>

=== adamkubina1/4iz238-final/pruvodce.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="pruvodce.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<?xml-stylesheet type="text/xsl" href="pruvodceHTML.xsl"?>

<průvodce xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:Test.Namespace pruvodce.xsd" 
    xmlns="urn:Test.Namespace">
    <názevDíla>Průvodce památkami</názevDíla>
    <autor>Klára Ťoupalíková</autor>
    <památky>
        <!-- Druh památky může být hrad, zámek, jiné -->
        <památka druh="hrad">
            <název>Kokořín</název>
            <postaven upřesnění="rok">1320</postaven>
            <!-- Oblíbenost může nabývat hodnot 0.0 - 5.0 -->
            <oblíbenost>4.6</oblíbenost>
            <!-- Tato památka je populárnější než: -->
            <památkaPoblíž>Strahovský klášter</památkaPoblíž>
            <umístění>
                <kraj>Středočeský kraj</kraj>
                <mapa href="https://goo.gl/maps/KWWkifuC6A72"/>
            </umístění>
            <sloh>Novogotika</sloh>
            <foto src="obrazky/kokorin.jpg"/>
            <popis>
                Hrad Kokořín se vypíná v pískovcových skalách Kokořínského dolu,
                nad údolím říčky Pšovky. Velmi přitažlivou krajinu Kokořínska tvoří 
                zajímavé skalní útvary, lesní porost, tůně, vzácné rostliny a živočichové, 
                divoká kaňonovitá údolí, historické památky, lidové stavby. Krajina byla 
                v roce 1976 vyhlášena Chráněnou krajinnou oblastí Kokořínsko.
                Do hradu přijdete po dřevěném mostě. Uvnitř je nádvoří a kousek nad ním 
                pokladna a suvenýry. Původní stavba vznikla během třináctého století a tvrz 
                částečně vytesanou do skály obývali tehdejší majitelé panství. Bohužel, 
                sedmnácté století se stalo dobou, kdy se hrad začal měnit na zříceninu. 
                Současný vzhled hradu Kokořín pochází z let 1911-1916, kdy došlo k úpravám. 
                Dominantu tvoří 38 m vysoká věž válvocitého tvaru s kamennou helmou. 
                Hradní palác se proti původnímu zvýšil o jedno patro, novodobé jsou malby 
                na stěnách a také vybavení místností.
            </popis>
            <zajímavost> Víte, že hrad byl řazen mezi tzv. prokleté hrady, tj. hrady, které se nesměly
                udržovat, protože jinak by díky své výhodné poloze mohly ohrozit panovnickou moc. </zajímavost>
            <majitelé>
                <majitel>Berkové z Dubé</majitel>
                <majitel>páni z Bezdědic</majitel>
                <majitel>Klinštejnové</majitel>
                <majitel>Beřkovští ze Šebířova</majitel>
                <majitel>Kaplířové ze Sulevic</majitel>
            </majitelé>
            <!-- Navštívitelnost hodnoty: ano/ne -->
            <navštívitelný>ano</navštívitelný>
            <vstupné měna="Kč">80</vstupné>
            <!-- Kdo může památku navštívit -->
            <přístupnost>
                <kategorie>pěší</kategorie>
                <kategorie>cyklo</kategorie>
                <kategorie>auto</kategorie>
                <kategorie>pejskaři</kategorie>
            </přístupnost>
            <služby>
                <služba>WC</služba>
                <služba>restaurace</služba>
                <služba>parkoviště</služba>
            </služby>
            <reference>
                <hodnocení>
                    <počet_hvězd>5</počet_hvězd>
                    <datum>2018-11-20</datum>
                    <komentář>
                        Je to prostě klasika. A je dobře, že to není další
                        zřícenina. Ano, rekonstrukce není historicky přesná atd.... 
                        Ale kde jinde dětem ukázat ten pravý romantický pohádkový hrad?
                    </komentář>
                </hodnocení>
                <hodnocení>
                    <počet_hvězd>4</počet_hvězd>
                    <datum>2018-10-23</datum>
                    <komentář>
                        Krasny malebny hrad. Je pravda trochu mensi. Za hodinku ani ne mate vse zkouknute(
                        velka prohlidka, bez cesty od park.). Pokud se extra nekochate a nevyzivate v informacich :)
                        Na mensi vylet idealni. Parkovani lze platit sms zpravou. 
                    </komentář>
                </hodnocení>
            </reference>
            <webovky href="http://hradkokorin.eu/"/>
        </památka>
        <památka druh="zámek">
            <název>Státní zámek Lednice</název>
            <postaven upřesnění="století">16</postaven>
            <oblíbenost>4.2</oblíbenost>
            <památkaPoblíž>Státní zámek Dačice</památkaPoblíž>
            <umístění>
                <kraj>Jihomoravský kraj</kraj>
                <mapa href="https://goo.gl/maps/SBrQsWN6tZw"/>
            </umístění>
            <sloh>Novogotika</sloh>
            <foto src="obrazky/zamek_lednice.jpg"/>
            <popis>
                Státní zámek Lednice je od roku 1945 majetkem státu, je spravován Ministerstvem 
                kultury ČR prostřednictvím Národního památkového ústavu Praha, územní odborné 
                pracoviště v Kroměříži. Zámek patří k nejnavštěvovanějším památkám v naší republice. 
                Novogotická přestavba v 19. století z něj vytvořila romantické sídlo obklopené jedním 
                z největších evropských parků (téměř 200 ha), ve kterém návštěvník najde palmový skleník, 
                benátskou kašnu, římský akvadukt, čínský pavilon, minaret a umělou zříceninu Janův hrad.            
            </popis>
            <zajímavost> Díky unikátnímu propojení stavebních památek s okolní člověkem formovanou
                přírodou byl v roce 1996 celý lednicko-valtický areál zapsán do seznamu světového
                dědictví UNESCO. </zajímavost>
            <majitelé>
                <majitel>Lichtenštejnové</majitel>
                <majitel>stát</majitel>
            </majitelé>
            <!-- Navštívitelnost hodnoty: ano/ne -->
            <navštívitelný>ano</navštívitelný>
            <vstupné měna="Kč">190</vstupné>
            <přístupnost>
                <kategorie>pěší</kategorie>
                <kategorie>cyklo</kategorie>
                <kategorie>auto</kategorie>
                <kategorie>bezbarierové</kategorie>
            </přístupnost>
            <služby>
                <služba>WC</služba>
                <služba>restaurace</služba>
                <služba>parkoviště</služba>
                <služba>prodejna rostlin</služba>
                <služba>fotografování</služba>
            </služby>
            <reference>
                <hodnocení>
                    <počet_hvězd>5</počet_hvězd>
                    <datum>2018-11-30</datum>
                    <komentář>
                        Nádherný zámek a zahrady. Jen je trochu problém v letních měsících 
                        s parkováním. Ale dá se to pochopit. 
                    </komentář>
                </hodnocení>            
            </reference>
            <webovky href="https://www.zamek-lednice.com/cs"/>
        </památka>
        <památka druh="jiné">
            <název>Strahovský klášter</název>
            <postaven upřesnění="rok">1143</postaven>
            <oblíbenost>4.3</oblíbenost>
            <památkaPoblíž>Kokořín</památkaPoblíž>
            <umístění>
                <kraj>Praha</kraj>
                <mapa href="https://goo.gl/maps/6FgzovD4gE42"/>
            </umístění>
            <sloh>barokní</sloh>
            <foto src="obrazky/strahovsky_klaster.jpg"/>
            <popis>Strahovský klášter, plným názvem Královská kanonie premonstrátů na Strahově, je nejstarší premonstrátský 
                klášter v Čechách, založený roku 1143, a jedna z nejvýznamnějších architektonických památek České republiky. 
                V klášteře, jehož konvent byl obnoven po roce 1990, sídlí také Památník národního písemnictví, součástí kláštera 
                je slavná Strahovská knihovna a obrazárna.
            </popis>
            <zajímavost>
                Strahovská knihovna je jednou z nejcennějších a nejlépe zachovaných historických knihoven nejen v Česku. Uchovává 
                přes 200 tisíc knih, z toho přes 3000 rukopisů a 1500 prvotisků, uložených ve zvláštním depozitáři. Knihovnu tvoří 
                dva sály, Teologický a větší Filosofický, a spojovací chodby mezi nimi.
            </zajímavost>
            <majitelé>
                <majitel>řád premonstrátů</majitel>
            </majitelé>
            <navštívitelný>ano</navštívitelný>
            <vstupné měna="Kč">120</vstupné>
            <přístupnost>
                <kategorie>pěší</kategorie>
                <kategorie>auto</kategorie>
            </přístupnost>
            <služby>
                <služba>ubytování</služba>
                <služba>WC</služba>
                <služba>restaurace</služba>
                <služba>pivovar</služba>
            </služby>
            <reference>
                <hodnocení>
                    <počet_hvězd>5</počet_hvězd>
                    <datum>2018-12-22</datum>
                    <komentář>
                        Jeden ze základních pilířů české vzdělanosti. Díky šikovnosti premonstrátů nebyl dokonce zrušen ani 
                        za Josefa ll. Knihovna v Teologickém i Filozofické sále je fascinující. Takových prostor u nás mnoho 
                        není (napadá mě broumovská klášterní knihovna). Při běžné prohlídce Vás do sálů knihovny nepustí, 
                        můžete jen nahlížet od dveří. My ovšem měli objednanou privátní prohlídku celé knihovny. Moc pěkné 
                        ale nekřesťansky drahé. Nicméně naším německým přátelům se moc líbilo. Pro vyjímečnou příležitost to stojí za to.
                        Pro získání běžného přehledu postačuje základní prohlídka. 
                    </komentář>
                </hodnocení>
